repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
      language_version: python3
      additional_dependencies: [
        flake8-bugbear,
        flake8-debugger,
        flake8-sfs,
        #flake8-docstrings,
      ]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    - id: python-safety-dependencies-check
      files: 'setup.py'
-   repo: local
    hooks:
    - id: pip-licenses
      name: pip-licenses
      # we ignore docutils because it has three licenses and the GPL license is for the emacs plugin as evidenced in their COPYING.txt.
      # This part is not distributed. This is evidenced by the MAINFEST.in
      entry: bash -c 'tox -e py39 --run-command "pip-licenses --ignore-packages docutils --fail-on=\"GNU General Public License (GPL);GNU General Public License v2 or later (GPLv2+)\""'
      language: system
      pass_filenames: false
-   repo: local
    hooks:
    - id: tests
      name: unit tests
      entry: pytest --mypy --disable-warnings -m "not benchmark"
      language: system
      types: [python]
      stages: [push, commit]
      always_run: true
      pass_filenames: false
    - id: license_and_required_marking
      name: license_and_required_marking
      entry: python3 update_license.py
      language: system
      pass_filenames: false
